webdriver.driver=chrome
webdriver.base.url=http://localhost:4000
serenity.project.name=Pruebas_Serenity
thucydides.project.name=Pruebas_Serenity
serenity.take.screenshots=AFTER_EACH_STEP
headless.mode=false
serenity.features.directory=src/test/resources/features
serenity.requirements.types=feature